# Generated by Django 5.0.14 on 2026-07-27 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Goods received'), ('SALE', 'Sale'), ('RETURN', 'Customer return'), ('TRANSFER_OUT', 'Transfer out (to another branch)'), ('TRANSFER_IN', 'Transfer in (from another branch)'), ('WASTAGE', 'Wastage / spoilage / damage'), ('STOCKTAKE_ADJUSTMENT', 'Physical count correction')], max_length=30)),
                ('quantity_delta', models.IntegerField(help_text='Signed. Positive adds stock, negative removes it.')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.CharField(blank=True, help_text="Free text, mainly for WASTAGE (e.g. 'expired', 'dropped', 'damaged in transit') and STOCKTAKE_ADJUSTMENT (e.g. 'annual count, June 2026').", max_length=255)),
                ('reference_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='branches.branch')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('reference_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'branch', 'created_at'], name='inventory_s_product_2cc34f_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'), models.Index(fields=['reference_content_type', 'reference_object_id'], name='inventory_s_referen_53b945_idx')],
            },
        ),
    ]
